In [49]:
import numpy as np
def showProduct(ma1,ma2):
    print(ma1)
    print("*")
    print(ma2)
    print("=")
    print(ma1 @ ma2)

def showProductM(ma1,ma2): # when 2 is a vector to be transposed
    print(ma1)
    print("*")
    print(ma2)
    print("=")
    print(np.matmul(ma1 ,np.transpose(ma2)))

In [50]:
function= np.array([[1,2,0],[3,0,-1]])
functionM= np.matrix([[1,2,0],[3,0,-1]])
a= np.array([2,-1,6])
b= np.array([-4,2,-12])
c= np.array([1,4,1])
d= np.array([4,-2,1])


In [51]:
showProduct(function,a)
showProductM(a, function)
#showProduct(function,b)
#showProduct(function,c)
showProduct(function,d)

[[ 1  2  0]
 [ 3  0 -1]]
*
[ 2 -1  6]
=
[0 0]
[ 2 -1  6]
*
[[ 1  2  0]
 [ 3  0 -1]]
=
[0 0]
[[ 1  2  0]
 [ 3  0 -1]]
*
[ 4 -2  1]
=
[ 0 11]


In [57]:
mx=np.matrix([[1,0,-1],[2,3,4]])
my=np.matrix([[3,0,1],[0,0,1],[2,6,0]])

showProduct(mx,my)

[[ 1  0 -1]
 [ 2  3  4]]
*
[[3 0 1]
 [0 0 1]
 [2 6 0]]
=
[[ 1 -6  1]
 [14 24  5]]


In [62]:
v= np.array([[1],[3],[5]])
vt = np.transpose(v)
print(v)
print(vt)
print(vt @ v)

[[1]
 [3]
 [5]]
[[1 3 5]]
[[35]]


In [63]:
v @ vt

array([[ 1,  3,  5],
       [ 3,  9, 15],
       [ 5, 15, 25]])